version: '3'

services:
  web:
    build: .
    command: /bin/sh -c "while ! nc -z db 5432; do sleep 2; done; ./entrypoint.sh"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - DATABASE_NAME=AvitoTech
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=123
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: AvitoTech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
