# Generated by Django 5.1.6 on 2025-02-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_transaction_merch_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="recipient_email",
            new_name="recipient_username",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="sender_email",
            new_name="sender_username",
        ),
    ]
