# Generated by Django 5.1.6 on 2025-02-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='coins',
            field=models.PositiveIntegerField(default=1000, help_text="User's coin balance."),
        ),
    ]
