# Generated by Django 5.1.6 on 2025-02-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_customuser_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='username', max_length=150, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
